services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: jobseeker
      POSTGRES_PASSWORD: jobseeker
      POSTGRES_DB: jobseeker_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  web:
    build: .
    command: python run.py
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: "True"
      DB_TYPE: postgresql
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: jobseeker_db
      DB_USER: jobseeker
      DB_PASSWORD: jobseeker
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  pgdata:
